### ISSUE TITLE
consular does not work on ruby 2.0.0-p0?

### ISSUE THREAD

**Issue by dfang** [achiu/consular-iterm#10]
there is only one line in my ~/.consularc , 
require 'consular/iterm'

i'm sure i installed consular consular-iterm gem . but still raises errors :

/Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require': cannot load such file -- _aem/mactypes (LoadError)
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in`require'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/rb-appscript-0.6.1/lib/appscript.rb:8:in `<top (required)>'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in`require'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/consular-iterm-1.0.2/lib/consular/iterm.rb:2:in`<top (required)>'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in`rescue in require'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/consular-1.0.2/bin/consular:14:in`<top (required)>'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/consular-1.0.2/bin/consular:10:in `instance_eval'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/consular-1.0.2/bin/consular:10:in`<top (required)>'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/bin/consular:23:in `load'
    from /Users/dfang/.rbenv/versions/2.0.0-p0/bin/consular:23:in`<main>'

**Comment by eric-hu** [comment]
Closing this as it was resolved with #12.  Bump version to 1.0.3 for a fix.
